name: FAP Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk-channel:
          - release
          - dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with ufbt
        id: build-app
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          sdk-channel: ${{ matrix.sdk-channel }}

      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.sdk-channel }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}

      - name: Lint sources
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          skip-setup: true
          task: lint
